version: '3.7'
services:
  mysql:
    image: mariadb:10.7.4
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - 'mysql:/var/lib/mysql'
  wordpress:
    build: .
    depends_on:
      - mysql
    image: wordpress
    ports:
      - '${WP_ENV_PORT:-8888}:80'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes: &ref_0
      - 'wordpress:/var/www/html'
      - >-
        ./vip-bases/vip-go-skeleton:/var/www/html/wp-content
      - >-
        ./vip-bases/vip-go-mu-plugins:/var/www/html/wp-content/mu-plugins
      - >-
        ./app/themes:/var/www/html/wp-content/themes
      - >-
        ./app/plugins:/var/www/html/wp-content/plugins
      - >-
        ./app/wp-config.php:/var/www/html/wp-config.php
  cli:
    depends_on:
      - wordpress
    image: 'wordpress:cli'
    volumes: *ref_0
    user: '33:33'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
volumes:
  wordpress: {}
  mysql: {}